### ISSUE TITLE
[Local Message] You exceeded your current quota. OpenAI以账户额度不足为由，拒绝服务.

### ISSUE THREAD

**Issue by Zhang2mm** [binary-husky/gpt_academic#394]
这个是每天被限额了吗，我用的ChatGPT普通账号，请大佬指导
![image](https://user-images.githubusercontent.com/76434131/230781643-1730977b-c14f-4994-9dbd-b366ce8ed3ff.png)

**Comment by RuSignalFlag** [comment]
5美元额度用完了吧  需要充值

**Comment by pigflyings** [comment]
换个新账号api继续用，或者绑一张虚拟信用卡嫖120刀（不建议）

**Comment by NameIsKevin** [comment]
怎么解决呢！我也遇到这个了

**Comment by NameIsKevin** [comment]
请问有解决办法了吗？是需要gpt4还是需要另外充钱呢



---原始邮件---
发件人: "Wei ***@***.***&gt;
发送时间: 2023年4月26日(周三) 凌晨0:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [binary-husky/gpt_academic] [Local Message] You exceeded your current quota. OpenAI以账户额度不足为由，拒绝服务. (Issue #394)




 
我的新账号API也不行，普通账号的。

**Comment by NameIsKevin** [comment]
好嘞 谢谢 有时间了解一下



---原始邮件---
发件人: "Wei ***@***.***&gt;
发送时间: 2023年4月26日(周三) 凌晨0:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [binary-husky/gpt_academic] [Local Message] You exceeded your current quota. OpenAI以账户额度不足为由，拒绝服务. (Issue #394)




  
请问有解决办法了吗？是需要gpt4还是需要另外充钱呢
 …
 ---原始邮件--- 发件人: "Wei @.&gt; 发送时间: 2023年4月26日(周三) 凌晨0:36 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [binary-husky/gpt_academic] [Local Message] You exceeded your current quota. OpenAI以账户额度不足为由，拒绝服务. (Issue #394) 我的新账号API也不行，普通账号的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
我看另一个issue说可以买一个几百余额的号，其他的解决办法暂时没有。

**Comment by houstonwhy** [comment]
请问责怎么解决呢，我买了plus账号，还是说余额不足

**Comment by Karenina-na** [comment]
> 请问责怎么解决呢，我买了plus账号，还是说余额不足
> 

可以用api2d试试
