### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by dev-mirzabicer** [binary-husky/gpt_academic#680]
This application looks quite amazing. Will there soon be an English language support?

**Comment by binary-husky** [comment]
I'm working on project self-translation, translating project source code to any language with chatgpt itself.

We already have a [plugin module](https://github.com/binary-husky/gpt_academic/blob/master/crazy_functions/%E4%BB%A3%E7%A0%81%E9%87%8D%E5%86%99%E4%B8%BA%E5%85%A8%E8%8B%B1%E6%96%87_%E5%A4%9A%E7%BA%BF%E7%A8%8B.py) to do similar job, however, it has not yet satisfy our expectation because of the token limitation problem.
