### ISSUE TITLE
[Bug]: [Local Message] 不能加载Newbing组件。

### ISSUE THREAD

**Issue by baiwei666** [binary-husky/gpt_academic#918]
### Installation Method | 安装方法与平台

Others (Please Describe)

### Version | 版本

Latest | 最新版

### OS | 操作系统

Windows

### Describe the bug | 简述

各位老师，我通过Windows一键脚本进行了安装，使用newbing模型，但出现了[Local Message] 不能加载Newbing组件的错误。cookies我已经输入了的，麻烦看看是什么问题吧

### Screen Shot | 有帮助的截图

![image](https://github.com/binary-husky/gpt_academic/assets/18593778/cc233017-5e57-4758-a922-64c8b8b96ae9)

**Comment by QuantumRoseinAmethystVase** [comment]
是因为没有把Bing.com加入代理

**Comment by baiwei666** [comment]
> 是因为没有把Bing.com加入代理 Same as #906

老师，要怎么设置呢？我是开了clash，还需要单独对脚本进士设置吗？

**Comment by baiwei666** [comment]
> 是因为没有把Bing.com加入代理 Same as #906

我在config.private.py设置成功了代理，可以使用newbing free，但无法使用newbing，是cookies设置有问题吗？请问具体要如何设置呢？我是在bing ai网站上通过cookie-editor插件整体导出cookies为json，然后粘贴进config.private.py

**Comment by QuantumRoseinAmethystVase** [comment]
> 

我没有newbing的cookies，回答不了

**Comment by Sillyringo** [comment]
I have attempted to use proxychains-ng and tsocks on MacOS, following the instructions provided at https://github.com/acheong08/EdgeGPT/issues/584#issuecomment-1615870064. However, I encountered conflicts between tools like tsocks and the conda environment set up for gpt_academic. The issue is illustrated below:

![image](https://github.com/binary-husky/gpt_academic/assets/43462278/01f1a0d3-dce1-467f-b562-af50f365d640)

Currently located in Guangzhou, I expected tsocks to change my IP location to Hong Kong. Unfortunately, this functionality failed when the conda environment created for gpt_academic was activated.
